services:
  fastapi:
    build: 
      context: .
      dockerfile: ./Dockerfile.backend
    container_name: fastapi
    volumes: 
      - .:/code
    ports: 
      - 80:80         #get rid of this once gradio is set up
    environment:
      OPENAPI_KEY: ${OPENAPI_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure:10"3
    depends_on:
      - postgres

  gradio:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: gradio
    volumes: 
      - .:/code
    ports: 
      - 7860:7860
    restart: on-failure:10"


  postgres:
    build: 
      context: .
      dockerfile: ./Dockerfile.pg
    container_name: postgres
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256  

    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
    ports: []
  