services:
  fastapi:
    build: 
      context: .
      dockerfile: ./Dockerfile.backend
    container_name: fastapi
    volumes: 
      - .:/code
    ports: 
      - 80:80
    restart: on-failure:10"3

    depends_on:
      - postgres

  gradio:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: gradio
    volumes: 
      - .:/code
    ports: 
      - 7860:7860
    restart: on-failure:10"


  postgres:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    container_name: postgres
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./pgdata:/var/lib/postgresql/data
      

    ports: []
  